import Pkg
Pkg.status()
Pkg.instantiate()
#Pkg.build()
#Pkg.activate("test")
#Pkg.status()
#Pkg.instantiate()
#Pkg.build()
using Pluto;
Pluto.activate_notebook_environment("ex1.jl")
Pkg.status()
Pkg.instantiate()
#Pkg.build()
Pluto.activate_notebook_environment("ex2.jl")
Pkg.status()
Pkg.instantiate()
#Pkg.build()
Pluto.activate_notebook_environment("ex3.jl")
Pkg.status()
Pkg.instantiate()
#Pkg.build()
